services:
  - type: web
    name: mergeverse-web
    env: docker
    plan: free
    repo: https://github.com/Minhson0112/Mergeverse
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: mergeverse-web
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mergeverse-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: mergeverse
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        generateValue: true
    autoDeploy: true

  - type: pserv
    name: mergeverse-db
    env: docker
    plan: free
    dockerfilePath: ''
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: mergeverse
      - key: MYSQL_USER
        value: user
      - key: MYSQL_PASSWORD
        generateValue: true
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1
